version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - type/deps
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.36
    - 14.14.41
    - 15.0.0
  - dependency-name: "@storybook/node-logger"
    versions:
    - 6.2.1
    - 6.2.2
    - 6.2.4
    - 6.2.5
    - 6.2.7
    - 6.2.8
    - 6.2.9
  - dependency-name: "@storybook/addon-a11y"
    versions:
    - 6.2.1
    - 6.2.2
    - 6.2.4
    - 6.2.5
    - 6.2.8
    - 6.2.9
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.8
    - 6.2.9
  - dependency-name: "@storybook/addon-docs"
    versions:
    - 6.2.9
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.9
    - 5.12.0
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.8
    - 6.2.9
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.2.1
    - 6.2.4
    - 6.2.5
    - 6.2.8
    - 6.2.9
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.0
    - 13.0.13
    - 13.0.16
    - 13.0.2
    - 13.0.7
    - 13.1.5
  - dependency-name: "@types/faker"
    versions:
    - 5.5.0
    - 5.5.3
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.8
  - dependency-name: faker
    versions:
    - 5.5.2
  - dependency-name: styled-components
    versions:
    - 5.2.2
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.8
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
    - 17.0.1
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.5
  - dependency-name: "@types/react-router-dom"
    versions:
    - 5.1.7
  - dependency-name: react
    versions:
    - 16.14.0
  - dependency-name: react-feather
    versions:
    - 2.0.9
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
