language: node_js
node_js:
- '11.10.1'
env:
  global:
  - secure: caFrDv25yuFVANtHHprrnLlhcLoVL6UBk+eQUKGdZFb6NUUF3VJ5sUU024oHy+eGDxcKRZLR+lu9h5FMIChTD7UGyHCd7aUUDtbz9sWGqnvGxKs4GEhySTVwIFvb2/9bI8danQuNrjgYWK4PqmeN3TZ6POg9s5dF7Nszne8FDVfdOZjDmb79TmXBUUE93Zil38VLJBE0rEmuM52M6eqE+NjtH5nqMRq+nFuBVJdLLoT5BHZFA2Zgnyw4pF51hxdFLSaMNsuLqMF/DK4jGfvxHpCN0OvuDyicWjoGgeMrYb1F+gpIF979URz/Iop8axMV6V8sWgm4AA3GzCwVr/FVcESIaFORYlLKrWUAb6TI+vrhpC9oW38Tg0oQrTxz8pjP8iNCM3gKfxP8hUAsgwuxM/DdbFapbN7vM5CtXbYvRbLXgMO/whlZnZ6WXA+wgier4ElgeFYdDwN2uneLsPwdaUQRqwJkII0sVLT0qamyW7efjyqJwQFxglAry7JTQzu5vxpMJ1WiaJQkwKza13L3SzL0+tZzPoxoaqNpeJPJFD8Jes31/BFYWZk6+kV+iMT606ZWaXhfCuGePr4m/5Z27ZtlDuWS49dIvPaUs4Yddz8kL7IVJBSoIXeOuqpW89wPN65eOz4AbcU5IGj6+Z7/zJx9hjWvAiV4wpBfU2CH8Qc=
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: release
    condition: "$TRAVIS_EVENT_TYPE = push"
  script:
  - bash ./scripts/ci/push_master.sh $GH_TOKEN
notifications:
  email: false
  slack:
    secure: LCAaF7RohWRV6EtxbvTphxSQCh1gHOdDt8HtdaEDy/xES4h0EM1IUfsY9/JXJe8B39LgdfzvIZdqREhIllDQ8aoMHBGvlimOmBIM9PLeM/qUmsko0ra2G19vMB721PLtpLVZh/SauVe0XXRwzkj3HwzDN7pPAwbyA0o0+0aSblZuBLTvWKcFSX4INopMS5hI9Z6Cc+8uTCNXtsjW5lR/sC2H6S8CGJYwh5xCx8lBAVu0/6iZq6PqGenb+7wK482f6c1R9hlNkufrUR/jpvPG8PtRPAWAOoRApEe34n8J1cK0/TjzpqPyHp9g5gYC+NrEc2IFMhhjHV+PmbnWp9X3GxHltaOGQRdqXvjDy9MXeEWbEjLlip+BuNxz4lvOJMbawDAohDA+69VDDqNByWU8E1hYH0ZiWTMDmK43Y5oRO1Nv2xI6WLEj/F5emudd17GievOwKH18rKd040VaTEWvh1T/mjC+HDfLPLRwOz8oP8th1WZM0WFFHZTqWfBmth62Hha28mlhp/RFHRpwJe1B3/E1pOy8I2VnQBEA7AkPcerG1LWoihSJqBNDtAj//amBtWxrwiRBZN7zWhqOg8Rr9SvbsB086A86Bwv6TglvWa5dWbItgBDfJfORXQ6+f+KN+FYph0X4BLyz+KSHrCsOCxkdJY64JT9pbkFk4IzaXk8=
