dist: bionic
language: node_js
node_js:
- 'node'

notifications:
  email: false
  slack:
    secure: LCAaF7RohWRV6EtxbvTphxSQCh1gHOdDt8HtdaEDy/xES4h0EM1IUfsY9/JXJe8B39LgdfzvIZdqREhIllDQ8aoMHBGvlimOmBIM9PLeM/qUmsko0ra2G19vMB721PLtpLVZh/SauVe0XXRwzkj3HwzDN7pPAwbyA0o0+0aSblZuBLTvWKcFSX4INopMS5hI9Z6Cc+8uTCNXtsjW5lR/sC2H6S8CGJYwh5xCx8lBAVu0/6iZq6PqGenb+7wK482f6c1R9hlNkufrUR/jpvPG8PtRPAWAOoRApEe34n8J1cK0/TjzpqPyHp9g5gYC+NrEc2IFMhhjHV+PmbnWp9X3GxHltaOGQRdqXvjDy9MXeEWbEjLlip+BuNxz4lvOJMbawDAohDA+69VDDqNByWU8E1hYH0ZiWTMDmK43Y5oRO1Nv2xI6WLEj/F5emudd17GievOwKH18rKd040VaTEWvh1T/mjC+HDfLPLRwOz8oP8th1WZM0WFFHZTqWfBmth62Hha28mlhp/RFHRpwJe1B3/E1pOy8I2VnQBEA7AkPcerG1LWoihSJqBNDtAj//amBtWxrwiRBZN7zWhqOg8Rr9SvbsB086A86Bwv6TglvWa5dWbItgBDfJfORXQ6+f+KN+FYph0X4BLyz+KSHrCsOCxkdJY64JT9pbkFk4IzaXk8=
