language: node_js
node_js:
  - "11"

env:
  global:
    - secure: "caFrDv25yuFVANtHHprrnLlhcLoVL6UBk+eQUKGdZFb6NUUF3VJ5sUU024oHy+eGDxcKRZLR+lu9h5FMIChTD7UGyHCd7aUUDtbz9sWGqnvGxKs4GEhySTVwIFvb2/9bI8danQuNrjgYWK4PqmeN3TZ6POg9s5dF7Nszne8FDVfdOZjDmb79TmXBUUE93Zil38VLJBE0rEmuM52M6eqE+NjtH5nqMRq+nFuBVJdLLoT5BHZFA2Zgnyw4pF51hxdFLSaMNsuLqMF/DK4jGfvxHpCN0OvuDyicWjoGgeMrYb1F+gpIF979URz/Iop8axMV6V8sWgm4AA3GzCwVr/FVcESIaFORYlLKrWUAb6TI+vrhpC9oW38Tg0oQrTxz8pjP8iNCM3gKfxP8hUAsgwuxM/DdbFapbN7vM5CtXbYvRbLXgMO/whlZnZ6WXA+wgier4ElgeFYdDwN2uneLsPwdaUQRqwJkII0sVLT0qamyW7efjyqJwQFxglAry7JTQzu5vxpMJ1WiaJQkwKza13L3SzL0+tZzPoxoaqNpeJPJFD8Jes31/BFYWZk6+kV+iMT606ZWaXhfCuGePr4m/5Z27ZtlDuWS49dIvPaUs4Yddz8kL7IVJBSoIXeOuqpW89wPN65eOz4AbcU5IGj6+Z7/zJx9hjWvAiV4wpBfU2CH8Qc="

# Build the client to the build/ directory
before_deploy:
  - npm run build

deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: release
    condition: $TRAVIS_EVENT_TYPE = push
  script:
    - git config user.email "travis@travis-ci.org"
    - git config user.name "Travis CI"
    - git checkout -b master
    - git add --force --all build
    - MESSAGE="CI build: $(git log --format=%B -n 1 $TRAVIS_COMMIT)"
    - git commit --message "$MESSAGE"
    - git remote add origin-deploy https://${GH_TOKEN}:x-oauth-basic@github.com/freecloudio/web.git > /dev/null 2>&1
    - git push --quiet origin-deploy master

