name: Freecloud Web

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install --check-cache
        name: "Check the yarn cache on PRs"
        if: github.event_name == 'pull_request'
      - run: yarn install
        name: "Yarn install without cache check"
        if: github.event_name != 'pull_request'
      - run: yarn test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install --check-cache
        name: "Check the yarn cache on PRs"
        if: github.event_name == 'pull_request'
      - run: yarn install
        name: "Yarn install without cache check"
        if: github.event_name != 'pull_request'
      - run: yarn build
