name: Freecloud Web

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        # FIXME: --force is needed on npm ci for a peer dependency version mismatch. Remove it once
        # the conflict gets resolved
        run: npm ci --ignore-scripts --force
      - name: Run unit tests
        # FIXME: The preflight checks currently fail due to a peer dependency version mismatch in
        # babel-loader. Remove the SKIP_PREFLIGHT_CHECK variable once this conflict is resolved
        run: SKIP_PREFLIGHT_CHECK=true npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        # FIXME: --force is needed on npm ci for a peer dependency version mismatch. Remove it once
        # the conflict gets resolved
        run: npm ci --ignore-scripts --force
      - name: Run a production build
        # FIXME: The preflight checks currently fail due to a peer dependency version mismatch in
        # babel-loader. Remove the SKIP_PREFLIGHT_CHECK variable once this conflict is resolved
        run: SKIP_PREFLIGHT_CHECK=true npm run build
